package com.example.user.center.dao;

import com.example.user.center.model.HouseProject;
import com.example.user.center.model.HouseProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    long countByExample(HouseProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByExample(HouseProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insert(HouseProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insertSelective(HouseProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    List<HouseProject> selectByExample(HouseProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    HouseProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") HouseProject record, @Param("example") HouseProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExample(@Param("record") HouseProject record, @Param("example") HouseProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKeySelective(HouseProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_project
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKey(HouseProject record);
}