package com.example.user.center.dao;

import com.example.user.center.model.HouseLibraryCategory;
import com.example.user.center.model.HouseLibraryCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseLibraryCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    long countByExample(HouseLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int deleteByExample(HouseLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int insert(HouseLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int insertSelective(HouseLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    List<HouseLibraryCategory> selectByExample(HouseLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    HouseLibraryCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") HouseLibraryCategory record, @Param("example") HouseLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int updateByExample(@Param("record") HouseLibraryCategory record, @Param("example") HouseLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int updateByPrimaryKeySelective(HouseLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category
     *
     * @mbg.generated Tue Feb 02 09:40:44 CST 2021
     */
    int updateByPrimaryKey(HouseLibraryCategory record);
}