package com.example.user.center.dao;

import com.example.user.center.model.HouseTowerLibraryCategory;
import com.example.user.center.model.HouseTowerLibraryCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseTowerLibraryCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    long countByExample(HouseTowerLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int deleteByExample(HouseTowerLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int insert(HouseTowerLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int insertSelective(HouseTowerLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    List<HouseTowerLibraryCategory> selectByExample(HouseTowerLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    HouseTowerLibraryCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") HouseTowerLibraryCategory record, @Param("example") HouseTowerLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int updateByExample(@Param("record") HouseTowerLibraryCategory record, @Param("example") HouseTowerLibraryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int updateByPrimaryKeySelective(HouseTowerLibraryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_library_category
     *
     * @mbg.generated Fri Jan 08 14:56:28 CST 2021
     */
    int updateByPrimaryKey(HouseTowerLibraryCategory record);
}