package com.example.user.center.dao;

import com.example.user.center.model.HouseTypeConstituteGroup;
import com.example.user.center.model.HouseTypeConstituteGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseTypeConstituteGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    long countByExample(HouseTypeConstituteGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int deleteByExample(HouseTypeConstituteGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int insert(HouseTypeConstituteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int insertSelective(HouseTypeConstituteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    List<HouseTypeConstituteGroup> selectByExample(HouseTypeConstituteGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    HouseTypeConstituteGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") HouseTypeConstituteGroup record, @Param("example") HouseTypeConstituteGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int updateByExample(@Param("record") HouseTypeConstituteGroup record, @Param("example") HouseTypeConstituteGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int updateByPrimaryKeySelective(HouseTypeConstituteGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    int updateByPrimaryKey(HouseTypeConstituteGroup record);
}