package com.example.user.center.dao;

import com.example.user.center.model.HouseFile;
import com.example.user.center.model.HouseFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    long countByExample(HouseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int deleteByExample(HouseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int insert(HouseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int insertSelective(HouseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    List<HouseFile> selectByExample(HouseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    HouseFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") HouseFile record, @Param("example") HouseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int updateByExample(@Param("record") HouseFile record, @Param("example") HouseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int updateByPrimaryKeySelective(HouseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_file
     *
     * @mbg.generated Tue Feb 02 10:35:45 CST 2021
     */
    int updateByPrimaryKey(HouseFile record);
}