package com.example.user.center.dao;

import com.example.user.center.model.HousePremisesLabel;
import com.example.user.center.model.HousePremisesLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HousePremisesLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    long countByExample(HousePremisesLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByExample(HousePremisesLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insert(HousePremisesLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insertSelective(HousePremisesLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    List<HousePremisesLabel> selectByExample(HousePremisesLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    HousePremisesLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") HousePremisesLabel record, @Param("example") HousePremisesLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExample(@Param("record") HousePremisesLabel record, @Param("example") HousePremisesLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKeySelective(HousePremisesLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKey(HousePremisesLabel record);
}