package com.example.user.center.dao;

import com.example.user.center.model.HouseAdministrative;
import com.example.user.center.model.HouseAdministrativeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseAdministrativeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    long countByExample(HouseAdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByExample(HouseAdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insert(HouseAdministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insertSelective(HouseAdministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    List<HouseAdministrative> selectByExample(HouseAdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    HouseAdministrative selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") HouseAdministrative record, @Param("example") HouseAdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExample(@Param("record") HouseAdministrative record, @Param("example") HouseAdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKeySelective(HouseAdministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_administrative
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKey(HouseAdministrative record);
}