package com.example.user.center.dao;

import com.example.user.center.model.HouseLibraryCategoryText;
import com.example.user.center.model.HouseLibraryCategoryTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseLibraryCategoryTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    long countByExample(HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int deleteByExample(HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int insert(HouseLibraryCategoryText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int insertSelective(HouseLibraryCategoryText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    List<HouseLibraryCategoryText> selectByExampleWithBLOBs(HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    List<HouseLibraryCategoryText> selectByExample(HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    HouseLibraryCategoryText selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") HouseLibraryCategoryText record, @Param("example") HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") HouseLibraryCategoryText record, @Param("example") HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByExample(@Param("record") HouseLibraryCategoryText record, @Param("example") HouseLibraryCategoryTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByPrimaryKeySelective(HouseLibraryCategoryText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(HouseLibraryCategoryText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_library_category_text
     *
     * @mbg.generated Tue Feb 02 09:41:13 CST 2021
     */
    int updateByPrimaryKey(HouseLibraryCategoryText record);
}