package com.example.user.center.dao;

import com.example.user.center.model.HouseTypeConstitute;
import com.example.user.center.model.HouseTypeConstituteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseTypeConstituteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    long countByExample(HouseTypeConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByExample(HouseTypeConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insert(HouseTypeConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int insertSelective(HouseTypeConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    List<HouseTypeConstitute> selectByExample(HouseTypeConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    HouseTypeConstitute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") HouseTypeConstitute record, @Param("example") HouseTypeConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByExample(@Param("record") HouseTypeConstitute record, @Param("example") HouseTypeConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKeySelective(HouseTypeConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    int updateByPrimaryKey(HouseTypeConstitute record);
}