package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class GameSlideshow implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.id
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.file
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.type
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.link
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.create_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.modify_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_slideshow.is_deleted
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_slideshow
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.id
     *
     * @return the value of game_slideshow.id
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.id
     *
     * @param id the value for game_slideshow.id
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.file
     *
     * @return the value of game_slideshow.file
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.file
     *
     * @param file the value for game_slideshow.file
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.type
     *
     * @return the value of game_slideshow.type
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.type
     *
     * @param type the value for game_slideshow.type
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.link
     *
     * @return the value of game_slideshow.link
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.link
     *
     * @param link the value for game_slideshow.link
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.create_date
     *
     * @return the value of game_slideshow.create_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.create_date
     *
     * @param createDate the value for game_slideshow.create_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.modify_date
     *
     * @return the value of game_slideshow.modify_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.modify_date
     *
     * @param modifyDate the value for game_slideshow.modify_date
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_slideshow.is_deleted
     *
     * @return the value of game_slideshow.is_deleted
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_slideshow.is_deleted
     *
     * @param isDeleted the value for game_slideshow.is_deleted
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_slideshow
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", file=").append(file);
        sb.append(", type=").append(type);
        sb.append(", link=").append(link);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}