package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class GameFormItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.name
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.form_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String formRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_form_item.form
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.id
     *
     * @return the value of game_form_item.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.id
     *
     * @param id the value for game_form_item.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.name
     *
     * @return the value of game_form_item.name
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.name
     *
     * @param name the value for game_form_item.name
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.type
     *
     * @return the value of game_form_item.type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.type
     *
     * @param type the value for game_form_item.type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.form_remark
     *
     * @return the value of game_form_item.form_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getFormRemark() {
        return formRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.form_remark
     *
     * @param formRemark the value for game_form_item.form_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setFormRemark(String formRemark) {
        this.formRemark = formRemark == null ? null : formRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.create_time
     *
     * @return the value of game_form_item.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.create_time
     *
     * @param createTime the value for game_form_item.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.modify_time
     *
     * @return the value of game_form_item.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.modify_time
     *
     * @param modifyTime the value for game_form_item.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.is_deleted
     *
     * @return the value of game_form_item.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.is_deleted
     *
     * @param isDeleted the value for game_form_item.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_form_item.form
     *
     * @return the value of game_form_item.form
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_form_item.form
     *
     * @param form the value for game_form_item.form
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", formRemark=").append(formRemark);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", form=").append(form);
        sb.append("]");
        return sb.toString();
    }
}