package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class GameOrders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.order_code
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.userinfo
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String userinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.order_status
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.user_id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.order_type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.hf_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String hfRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.last_modifier
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_orders.order_detail
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private String orderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_orders
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.id
     *
     * @return the value of game_orders.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.id
     *
     * @param id the value for game_orders.id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.order_code
     *
     * @return the value of game_orders.order_code
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.order_code
     *
     * @param orderCode the value for game_orders.order_code
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.userinfo
     *
     * @return the value of game_orders.userinfo
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getUserinfo() {
        return userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.userinfo
     *
     * @param userinfo the value for game_orders.userinfo
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setUserinfo(String userinfo) {
        this.userinfo = userinfo == null ? null : userinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.order_status
     *
     * @return the value of game_orders.order_status
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.order_status
     *
     * @param orderStatus the value for game_orders.order_status
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.user_id
     *
     * @return the value of game_orders.user_id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.user_id
     *
     * @param userId the value for game_orders.user_id
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.order_type
     *
     * @return the value of game_orders.order_type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.order_type
     *
     * @param orderType the value for game_orders.order_type
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.hf_remark
     *
     * @return the value of game_orders.hf_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getHfRemark() {
        return hfRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.hf_remark
     *
     * @param hfRemark the value for game_orders.hf_remark
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setHfRemark(String hfRemark) {
        this.hfRemark = hfRemark == null ? null : hfRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.create_time
     *
     * @return the value of game_orders.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.create_time
     *
     * @param createTime the value for game_orders.create_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.modify_time
     *
     * @return the value of game_orders.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.modify_time
     *
     * @param modifyTime the value for game_orders.modify_time
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.last_modifier
     *
     * @return the value of game_orders.last_modifier
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.last_modifier
     *
     * @param lastModifier the value for game_orders.last_modifier
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.is_deleted
     *
     * @return the value of game_orders.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.is_deleted
     *
     * @param isDeleted the value for game_orders.is_deleted
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_orders.order_detail
     *
     * @return the value of game_orders.order_detail
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_orders.order_detail
     *
     * @param orderDetail the value for game_orders.order_detail
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail == null ? null : orderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_orders
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderCode=").append(orderCode);
        sb.append(", userinfo=").append(userinfo);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", userId=").append(userId);
        sb.append(", orderType=").append(orderType);
        sb.append(", hfRemark=").append(hfRemark);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", lastModifier=").append(lastModifier);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", orderDetail=").append(orderDetail);
        sb.append("]");
        return sb.toString();
    }
}