package com.example.admin.center.dao;

import com.example.admin.center.model.GameForm;
import com.example.admin.center.model.GameFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    long countByExample(GameFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int deleteByExample(GameFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int insert(GameForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int insertSelective(GameForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    List<GameForm> selectByExample(GameFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    GameForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") GameForm record, @Param("example") GameFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int updateByExample(@Param("record") GameForm record, @Param("example") GameFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int updateByPrimaryKeySelective(GameForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form
     *
     * @mbg.generated Tue Jan 19 10:02:05 CST 2021
     */
    int updateByPrimaryKey(GameForm record);
}