package com.example.admin.center.dao;

import com.example.admin.center.model.GameFormItem;
import com.example.admin.center.model.GameFormItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameFormItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    long countByExample(GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int deleteByExample(GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int insert(GameFormItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int insertSelective(GameFormItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    List<GameFormItem> selectByExampleWithBLOBs(GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    List<GameFormItem> selectByExample(GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    GameFormItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") GameFormItem record, @Param("example") GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") GameFormItem record, @Param("example") GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByExample(@Param("record") GameFormItem record, @Param("example") GameFormItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByPrimaryKeySelective(GameFormItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(GameFormItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_form_item
     *
     * @mbg.generated Wed Jan 20 09:08:18 CST 2021
     */
    int updateByPrimaryKey(GameFormItem record);
}