package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HotelUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.email
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.phone
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.identity_card
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String identityCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.identity_region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String identityRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.identity_address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String identityAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.nick_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.real_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.sex
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.birth_day
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.user_status
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Byte userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.user_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.file
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.source_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.last_auth_time
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime lastAuthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_user.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_user
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.id
     *
     * @return the value of hotel_user.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.id
     *
     * @param id the value for hotel_user.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.email
     *
     * @return the value of hotel_user.email
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.email
     *
     * @param email the value for hotel_user.email
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.phone
     *
     * @return the value of hotel_user.phone
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.phone
     *
     * @param phone the value for hotel_user.phone
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.identity_card
     *
     * @return the value of hotel_user.identity_card
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.identity_card
     *
     * @param identityCard the value for hotel_user.identity_card
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.identity_region
     *
     * @return the value of hotel_user.identity_region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getIdentityRegion() {
        return identityRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.identity_region
     *
     * @param identityRegion the value for hotel_user.identity_region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setIdentityRegion(String identityRegion) {
        this.identityRegion = identityRegion == null ? null : identityRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.identity_address
     *
     * @return the value of hotel_user.identity_address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getIdentityAddress() {
        return identityAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.identity_address
     *
     * @param identityAddress the value for hotel_user.identity_address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setIdentityAddress(String identityAddress) {
        this.identityAddress = identityAddress == null ? null : identityAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.nick_name
     *
     * @return the value of hotel_user.nick_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.nick_name
     *
     * @param nickName the value for hotel_user.nick_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.real_name
     *
     * @return the value of hotel_user.real_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.real_name
     *
     * @param realName the value for hotel_user.real_name
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.sex
     *
     * @return the value of hotel_user.sex
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.sex
     *
     * @param sex the value for hotel_user.sex
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.birth_day
     *
     * @return the value of hotel_user.birth_day
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.birth_day
     *
     * @param birthDay the value for hotel_user.birth_day
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setBirthDay(LocalDateTime birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.user_status
     *
     * @return the value of hotel_user.user_status
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.user_status
     *
     * @param userStatus the value for hotel_user.user_status
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.user_type
     *
     * @return the value of hotel_user.user_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.user_type
     *
     * @param userType the value for hotel_user.user_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.file
     *
     * @return the value of hotel_user.file
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.file
     *
     * @param file the value for hotel_user.file
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.address
     *
     * @return the value of hotel_user.address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.address
     *
     * @param address the value for hotel_user.address
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.source_type
     *
     * @return the value of hotel_user.source_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.source_type
     *
     * @param sourceType the value for hotel_user.source_type
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.last_auth_time
     *
     * @return the value of hotel_user.last_auth_time
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getLastAuthTime() {
        return lastAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.last_auth_time
     *
     * @param lastAuthTime the value for hotel_user.last_auth_time
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setLastAuthTime(LocalDateTime lastAuthTime) {
        this.lastAuthTime = lastAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.region
     *
     * @return the value of hotel_user.region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.region
     *
     * @param region the value for hotel_user.region
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.create_date
     *
     * @return the value of hotel_user.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.create_date
     *
     * @param createDate the value for hotel_user.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.modify_date
     *
     * @return the value of hotel_user.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.modify_date
     *
     * @param modifyDate the value for hotel_user.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_user.is_deleted
     *
     * @return the value of hotel_user.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_user.is_deleted
     *
     * @param isDeleted the value for hotel_user.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_user
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", identityCard=").append(identityCard);
        sb.append(", identityRegion=").append(identityRegion);
        sb.append(", identityAddress=").append(identityAddress);
        sb.append(", nickName=").append(nickName);
        sb.append(", realName=").append(realName);
        sb.append(", sex=").append(sex);
        sb.append(", birthDay=").append(birthDay);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", userType=").append(userType);
        sb.append(", file=").append(file);
        sb.append(", address=").append(address);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", lastAuthTime=").append(lastAuthTime);
        sb.append(", region=").append(region);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}