package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HotelProtocol implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_protocol.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_protocol.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_protocol.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_protocol.id_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private Byte idDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_protocol.protocol
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_protocol
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_protocol.id
     *
     * @return the value of hotel_protocol.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_protocol.id
     *
     * @param id the value for hotel_protocol.id
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_protocol.create_date
     *
     * @return the value of hotel_protocol.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_protocol.create_date
     *
     * @param createDate the value for hotel_protocol.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_protocol.modify_date
     *
     * @return the value of hotel_protocol.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_protocol.modify_date
     *
     * @param modifyDate the value for hotel_protocol.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_protocol.id_deleted
     *
     * @return the value of hotel_protocol.id_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public Byte getIdDeleted() {
        return idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_protocol.id_deleted
     *
     * @param idDeleted the value for hotel_protocol.id_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setIdDeleted(Byte idDeleted) {
        this.idDeleted = idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_protocol.protocol
     *
     * @return the value of hotel_protocol.protocol
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_protocol.protocol
     *
     * @param protocol the value for hotel_protocol.protocol
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_protocol
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", idDeleted=").append(idDeleted);
        sb.append(", protocol=").append(protocol);
        sb.append("]");
        return sb.toString();
    }
}