package com.example.admin.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HotelCart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.cart_code
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private String cartCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.product_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.quantity
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.user_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.state
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_cart.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.id
     *
     * @return the value of hotel_cart.id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.id
     *
     * @param id the value for hotel_cart.id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.cart_code
     *
     * @return the value of hotel_cart.cart_code
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public String getCartCode() {
        return cartCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.cart_code
     *
     * @param cartCode the value for hotel_cart.cart_code
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setCartCode(String cartCode) {
        this.cartCode = cartCode == null ? null : cartCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.product_id
     *
     * @return the value of hotel_cart.product_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.product_id
     *
     * @param productId the value for hotel_cart.product_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.quantity
     *
     * @return the value of hotel_cart.quantity
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.quantity
     *
     * @param quantity the value for hotel_cart.quantity
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.user_id
     *
     * @return the value of hotel_cart.user_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.user_id
     *
     * @param userId the value for hotel_cart.user_id
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.state
     *
     * @return the value of hotel_cart.state
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.state
     *
     * @param state the value for hotel_cart.state
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.create_date
     *
     * @return the value of hotel_cart.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.create_date
     *
     * @param createDate the value for hotel_cart.create_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.modify_date
     *
     * @return the value of hotel_cart.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.modify_date
     *
     * @param modifyDate the value for hotel_cart.modify_date
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_cart.is_deleted
     *
     * @return the value of hotel_cart.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_cart.is_deleted
     *
     * @param isDeleted the value for hotel_cart.is_deleted
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cartCode=").append(cartCode);
        sb.append(", productId=").append(productId);
        sb.append(", quantity=").append(quantity);
        sb.append(", userId=").append(userId);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}