spring:
  aop:
    proxy-target-class: true
  application:
    name: game-center
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://39.99.157.7:3306/game?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: Davin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select now()
      idle-timeout: 3000000
      auto-commit: true
      max-lifetime: 1200000
      maximum-pool-size: 60
      minimum-idle: 10
      login-timeout: 5
      validation-timeout: 300000
      connection-timeout: 60000
      read-only: false
  redis:
    database: 0
    host: 39.99.157.7
    port: 6379
    password: 123456
    timeout: 10000
    jedis:
      pool:
        max-active: 16
        max-idle: 4
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 3600s
server:
  port: 7003
  servlet:
    context-path: /game
logging:
  file: ./logs/king-words.log
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka

mybatis:
  mapper-locations:
      - mappers/*.xml
      - manual-mappers/*.xml
