spring:
  aop:
    proxy-target-class: true
  application:
    name: product-center
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
      host: 39.100.237.144
      port: 5672
      username: sw
      password: Davin1203!
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://39.98.126.20:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: hanfu_admin
    password: Davin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select now()
      idle-timeout: 3000000
      auto-commit: true
      max-lifetime: 1200000
      maximum-pool-size: 60
      minimum-idle: 10
      login-timeout: 5
      validation-timeout: 300000
      connection-timeout: 60000
      read-only: false
  redis:
    database: 0
    host: 39.100.237.144
    port: 16379
    timeout: 10000ms
    jedis:
      pool:
        max-active: 16
        max-idle: 4
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 3600s
server:
  port: 7002
  servlet:
    context-path: /product
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
logging:
  file: ./logs/king-words.log

mybatis:
  mapper-locations:
      - mappers/*.xml
      - manual-mappers/*.xml
