package com.example.user.center.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class HousePremises implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.premises_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String premisesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.land_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer landId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.price
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.opening_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime openingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.developers_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String developersName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.households
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer households;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.property_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.site_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double siteArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.architecture_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double architectureArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.plot_ratio
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double plotRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_premises
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.id
     *
     * @return the value of house_premises.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.id
     *
     * @param id the value for house_premises.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.premises_name
     *
     * @return the value of house_premises.premises_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getPremisesName() {
        return premisesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.premises_name
     *
     * @param premisesName the value for house_premises.premises_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPremisesName(String premisesName) {
        this.premisesName = premisesName == null ? null : premisesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.land_id
     *
     * @return the value of house_premises.land_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getLandId() {
        return landId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.land_id
     *
     * @param landId the value for house_premises.land_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLandId(Integer landId) {
        this.landId = landId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.price
     *
     * @return the value of house_premises.price
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.price
     *
     * @param price the value for house_premises.price
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.opening_time
     *
     * @return the value of house_premises.opening_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.opening_time
     *
     * @param openingTime the value for house_premises.opening_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setOpeningTime(LocalDateTime openingTime) {
        this.openingTime = openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.developers_name
     *
     * @return the value of house_premises.developers_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getDevelopersName() {
        return developersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.developers_name
     *
     * @param developersName the value for house_premises.developers_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setDevelopersName(String developersName) {
        this.developersName = developersName == null ? null : developersName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.households
     *
     * @return the value of house_premises.households
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getHouseholds() {
        return households;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.households
     *
     * @param households the value for house_premises.households
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setHouseholds(Integer households) {
        this.households = households;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.property_name
     *
     * @return the value of house_premises.property_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.property_name
     *
     * @param propertyName the value for house_premises.property_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.site_area
     *
     * @return the value of house_premises.site_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getSiteArea() {
        return siteArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.site_area
     *
     * @param siteArea the value for house_premises.site_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setSiteArea(Double siteArea) {
        this.siteArea = siteArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.architecture_area
     *
     * @return the value of house_premises.architecture_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getArchitectureArea() {
        return architectureArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.architecture_area
     *
     * @param architectureArea the value for house_premises.architecture_area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setArchitectureArea(Double architectureArea) {
        this.architectureArea = architectureArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.plot_ratio
     *
     * @return the value of house_premises.plot_ratio
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getPlotRatio() {
        return plotRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.plot_ratio
     *
     * @param plotRatio the value for house_premises.plot_ratio
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPlotRatio(Double plotRatio) {
        this.plotRatio = plotRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.create_date
     *
     * @return the value of house_premises.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.create_date
     *
     * @param createDate the value for house_premises.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.modify_date
     *
     * @return the value of house_premises.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.modify_date
     *
     * @param modifyDate the value for house_premises.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises.is_deleted
     *
     * @return the value of house_premises.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises.is_deleted
     *
     * @param isDeleted the value for house_premises.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", premisesName=").append(premisesName);
        sb.append(", landId=").append(landId);
        sb.append(", price=").append(price);
        sb.append(", openingTime=").append(openingTime);
        sb.append(", developersName=").append(developersName);
        sb.append(", households=").append(households);
        sb.append(", propertyName=").append(propertyName);
        sb.append(", siteArea=").append(siteArea);
        sb.append(", architectureArea=").append(architectureArea);
        sb.append(", plotRatio=").append(plotRatio);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}