package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseTowerNo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.sequence
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private String sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.tower_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private String towerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.premises_id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private Integer premisesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.synchronization_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private Integer synchronizationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.state
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.create_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.modify_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tower_no.is_deleted
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_tower_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.id
     *
     * @return the value of house_tower_no.id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.id
     *
     * @param id the value for house_tower_no.id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.sequence
     *
     * @return the value of house_tower_no.sequence
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.sequence
     *
     * @param sequence the value for house_tower_no.sequence
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setSequence(String sequence) {
        this.sequence = sequence == null ? null : sequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.tower_no
     *
     * @return the value of house_tower_no.tower_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public String getTowerNo() {
        return towerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.tower_no
     *
     * @param towerNo the value for house_tower_no.tower_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setTowerNo(String towerNo) {
        this.towerNo = towerNo == null ? null : towerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.premises_id
     *
     * @return the value of house_tower_no.premises_id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public Integer getPremisesId() {
        return premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.premises_id
     *
     * @param premisesId the value for house_tower_no.premises_id
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setPremisesId(Integer premisesId) {
        this.premisesId = premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.synchronization_no
     *
     * @return the value of house_tower_no.synchronization_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public Integer getSynchronizationNo() {
        return synchronizationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.synchronization_no
     *
     * @param synchronizationNo the value for house_tower_no.synchronization_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setSynchronizationNo(Integer synchronizationNo) {
        this.synchronizationNo = synchronizationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.state
     *
     * @return the value of house_tower_no.state
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.state
     *
     * @param state the value for house_tower_no.state
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.create_date
     *
     * @return the value of house_tower_no.create_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.create_date
     *
     * @param createDate the value for house_tower_no.create_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.modify_date
     *
     * @return the value of house_tower_no.modify_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.modify_date
     *
     * @param modifyDate the value for house_tower_no.modify_date
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tower_no.is_deleted
     *
     * @return the value of house_tower_no.is_deleted
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tower_no.is_deleted
     *
     * @param isDeleted the value for house_tower_no.is_deleted
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tower_no
     *
     * @mbg.generated Tue Feb 23 17:44:38 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sequence=").append(sequence);
        sb.append(", towerNo=").append(towerNo);
        sb.append(", premisesId=").append(premisesId);
        sb.append(", synchronizationNo=").append(synchronizationNo);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}