package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseLabel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.label_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.label_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String labelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.label_state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String labelState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_label.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.id
     *
     * @return the value of house_label.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.id
     *
     * @param id the value for house_label.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.label_name
     *
     * @return the value of house_label.label_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.label_name
     *
     * @param labelName the value for house_label.label_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.label_type
     *
     * @return the value of house_label.label_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getLabelType() {
        return labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.label_type
     *
     * @param labelType the value for house_label.label_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLabelType(String labelType) {
        this.labelType = labelType == null ? null : labelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.label_state
     *
     * @return the value of house_label.label_state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getLabelState() {
        return labelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.label_state
     *
     * @param labelState the value for house_label.label_state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLabelState(String labelState) {
        this.labelState = labelState == null ? null : labelState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.create_date
     *
     * @return the value of house_label.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.create_date
     *
     * @param createDate the value for house_label.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.modify_date
     *
     * @return the value of house_label.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.modify_date
     *
     * @param modifyDate the value for house_label.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_label.is_deleted
     *
     * @return the value of house_label.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_label.is_deleted
     *
     * @param isDeleted the value for house_label.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_label
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", labelName=").append(labelName);
        sb.append(", labelType=").append(labelType);
        sb.append(", labelState=").append(labelState);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}