package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HousePremisesPicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.premises_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer premisesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.file
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_premises_picture.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_premises_picture
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.id
     *
     * @return the value of house_premises_picture.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.id
     *
     * @param id the value for house_premises_picture.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.premises_id
     *
     * @return the value of house_premises_picture.premises_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getPremisesId() {
        return premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.premises_id
     *
     * @param premisesId the value for house_premises_picture.premises_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPremisesId(Integer premisesId) {
        this.premisesId = premisesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.file
     *
     * @return the value of house_premises_picture.file
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.file
     *
     * @param file the value for house_premises_picture.file
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.state
     *
     * @return the value of house_premises_picture.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.state
     *
     * @param state the value for house_premises_picture.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.type
     *
     * @return the value of house_premises_picture.type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.type
     *
     * @param type the value for house_premises_picture.type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.create_date
     *
     * @return the value of house_premises_picture.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.create_date
     *
     * @param createDate the value for house_premises_picture.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.modify_date
     *
     * @return the value of house_premises_picture.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.modify_date
     *
     * @param modifyDate the value for house_premises_picture.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_premises_picture.is_deleted
     *
     * @return the value of house_premises_picture.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_premises_picture.is_deleted
     *
     * @param isDeleted the value for house_premises_picture.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_premises_picture
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", premisesId=").append(premisesId);
        sb.append(", file=").append(file);
        sb.append(", state=").append(state);
        sb.append(", type=").append(type);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}