package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.user_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.auth_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.auth_key
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String authKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.pass_word
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.auth_status
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String authStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.last_auth_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime lastAuthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_auth.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_auth
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.id
     *
     * @return the value of house_auth.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.id
     *
     * @param id the value for house_auth.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.user_id
     *
     * @return the value of house_auth.user_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.user_id
     *
     * @param userId the value for house_auth.user_id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.auth_type
     *
     * @return the value of house_auth.auth_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.auth_type
     *
     * @param authType the value for house_auth.auth_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setAuthType(String authType) {
        this.authType = authType == null ? null : authType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.auth_key
     *
     * @return the value of house_auth.auth_key
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getAuthKey() {
        return authKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.auth_key
     *
     * @param authKey the value for house_auth.auth_key
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setAuthKey(String authKey) {
        this.authKey = authKey == null ? null : authKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.pass_word
     *
     * @return the value of house_auth.pass_word
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.pass_word
     *
     * @param passWord the value for house_auth.pass_word
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.auth_status
     *
     * @return the value of house_auth.auth_status
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.auth_status
     *
     * @param authStatus the value for house_auth.auth_status
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setAuthStatus(String authStatus) {
        this.authStatus = authStatus == null ? null : authStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.last_auth_time
     *
     * @return the value of house_auth.last_auth_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getLastAuthTime() {
        return lastAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.last_auth_time
     *
     * @param lastAuthTime the value for house_auth.last_auth_time
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLastAuthTime(LocalDateTime lastAuthTime) {
        this.lastAuthTime = lastAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.create_date
     *
     * @return the value of house_auth.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.create_date
     *
     * @param createDate the value for house_auth.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.modify_date
     *
     * @return the value of house_auth.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.modify_date
     *
     * @param modifyDate the value for house_auth.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_auth.is_deleted
     *
     * @return the value of house_auth.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_auth.is_deleted
     *
     * @param isDeleted the value for house_auth.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_auth
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", authType=").append(authType);
        sb.append(", authKey=").append(authKey);
        sb.append(", passWord=").append(passWord);
        sb.append(", authStatus=").append(authStatus);
        sb.append(", lastAuthTime=").append(lastAuthTime);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}