package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.house_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String houseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.supply
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer supply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.transaction
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer transaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.south_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double southWide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.living_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double livingWide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.master_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double masterWide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.guest_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Double guestWide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.id
     *
     * @return the value of house_type.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.id
     *
     * @param id the value for house_type.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.house_name
     *
     * @return the value of house_type.house_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.house_name
     *
     * @param houseName the value for house_type.house_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.area
     *
     * @return the value of house_type.area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.area
     *
     * @param area the value for house_type.area
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.supply
     *
     * @return the value of house_type.supply
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getSupply() {
        return supply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.supply
     *
     * @param supply the value for house_type.supply
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setSupply(Integer supply) {
        this.supply = supply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.transaction
     *
     * @return the value of house_type.transaction
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.transaction
     *
     * @param transaction the value for house_type.transaction
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setTransaction(Integer transaction) {
        this.transaction = transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.south_wide
     *
     * @return the value of house_type.south_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getSouthWide() {
        return southWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.south_wide
     *
     * @param southWide the value for house_type.south_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setSouthWide(Double southWide) {
        this.southWide = southWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.living_wide
     *
     * @return the value of house_type.living_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getLivingWide() {
        return livingWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.living_wide
     *
     * @param livingWide the value for house_type.living_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setLivingWide(Double livingWide) {
        this.livingWide = livingWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.master_wide
     *
     * @return the value of house_type.master_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getMasterWide() {
        return masterWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.master_wide
     *
     * @param masterWide the value for house_type.master_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setMasterWide(Double masterWide) {
        this.masterWide = masterWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.guest_wide
     *
     * @return the value of house_type.guest_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Double getGuestWide() {
        return guestWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.guest_wide
     *
     * @param guestWide the value for house_type.guest_wide
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setGuestWide(Double guestWide) {
        this.guestWide = guestWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.create_date
     *
     * @return the value of house_type.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.create_date
     *
     * @param createDate the value for house_type.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.modify_date
     *
     * @return the value of house_type.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.modify_date
     *
     * @param modifyDate the value for house_type.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.is_deleted
     *
     * @return the value of house_type.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.is_deleted
     *
     * @param isDeleted the value for house_type.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", houseName=").append(houseName);
        sb.append(", area=").append(area);
        sb.append(", supply=").append(supply);
        sb.append(", transaction=").append(transaction);
        sb.append(", southWide=").append(southWide);
        sb.append(", livingWide=").append(livingWide);
        sb.append(", masterWide=").append(masterWide);
        sb.append(", guestWide=").append(guestWide);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}