package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseTypeConstituteGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.constitute_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private Integer constituteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.type_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.value
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private Double value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.create_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.modify_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute_group.is_deleted
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.id
     *
     * @return the value of house_type_constitute_group.id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.id
     *
     * @param id the value for house_type_constitute_group.id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.constitute_id
     *
     * @return the value of house_type_constitute_group.constitute_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public Integer getConstituteId() {
        return constituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.constitute_id
     *
     * @param constituteId the value for house_type_constitute_group.constitute_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setConstituteId(Integer constituteId) {
        this.constituteId = constituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.type_id
     *
     * @return the value of house_type_constitute_group.type_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.type_id
     *
     * @param typeId the value for house_type_constitute_group.type_id
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.value
     *
     * @return the value of house_type_constitute_group.value
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.value
     *
     * @param value the value for house_type_constitute_group.value
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.create_date
     *
     * @return the value of house_type_constitute_group.create_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.create_date
     *
     * @param createDate the value for house_type_constitute_group.create_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.modify_date
     *
     * @return the value of house_type_constitute_group.modify_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.modify_date
     *
     * @param modifyDate the value for house_type_constitute_group.modify_date
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute_group.is_deleted
     *
     * @return the value of house_type_constitute_group.is_deleted
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute_group.is_deleted
     *
     * @param isDeleted the value for house_type_constitute_group.is_deleted
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute_group
     *
     * @mbg.generated Mon Jan 04 15:32:11 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", constituteId=").append(constituteId);
        sb.append(", typeId=").append(typeId);
        sb.append(", value=").append(value);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}