package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HouseTypeConstitute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.constitute_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String constituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type_constitute.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.id
     *
     * @return the value of house_type_constitute.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.id
     *
     * @param id the value for house_type_constitute.id
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.constitute_name
     *
     * @return the value of house_type_constitute.constitute_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getConstituteName() {
        return constituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.constitute_name
     *
     * @param constituteName the value for house_type_constitute.constitute_name
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setConstituteName(String constituteName) {
        this.constituteName = constituteName == null ? null : constituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.state
     *
     * @return the value of house_type_constitute.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.state
     *
     * @param state the value for house_type_constitute.state
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.create_date
     *
     * @return the value of house_type_constitute.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.create_date
     *
     * @param createDate the value for house_type_constitute.create_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.modify_date
     *
     * @return the value of house_type_constitute.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.modify_date
     *
     * @param modifyDate the value for house_type_constitute.modify_date
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type_constitute.is_deleted
     *
     * @return the value of house_type_constitute.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type_constitute.is_deleted
     *
     * @param isDeleted the value for house_type_constitute.is_deleted
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type_constitute
     *
     * @mbg.generated Thu Dec 31 10:09:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", constituteName=").append(constituteName);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}