package com.example.admin.center.dao;

import com.example.admin.center.model.HotelCart;
import com.example.admin.center.model.HotelCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    long countByExample(HotelCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByExample(HotelCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insert(HotelCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insertSelective(HotelCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    List<HotelCart> selectByExample(HotelCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    HotelCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") HotelCart record, @Param("example") HotelCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByExample(@Param("record") HotelCart record, @Param("example") HotelCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByPrimaryKeySelective(HotelCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_cart
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByPrimaryKey(HotelCart record);
}