package com.example.admin.center.dao;

import com.example.admin.center.model.HotelProduct;
import com.example.admin.center.model.HotelProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    long countByExample(HotelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByExample(HotelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insert(HotelProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insertSelective(HotelProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    List<HotelProduct> selectByExample(HotelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    HotelProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") HotelProduct record, @Param("example") HotelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    int updateByExample(@Param("record") HotelProduct record, @Param("example") HotelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    int updateByPrimaryKeySelective(HotelProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_product
     *
     * @mbg.generated Tue Jan 12 11:21:12 CST 2021
     */
    int updateByPrimaryKey(HotelProduct record);
}