package com.example.admin.center.dao;

import com.example.admin.center.model.HotelOrdersDetail;
import com.example.admin.center.model.HotelOrdersDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelOrdersDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    long countByExample(HotelOrdersDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByExample(HotelOrdersDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insert(HotelOrdersDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int insertSelective(HotelOrdersDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    List<HotelOrdersDetail> selectByExample(HotelOrdersDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    HotelOrdersDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") HotelOrdersDetail record, @Param("example") HotelOrdersDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByExample(@Param("record") HotelOrdersDetail record, @Param("example") HotelOrdersDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByPrimaryKeySelective(HotelOrdersDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_orders_detail
     *
     * @mbg.generated Tue Jan 12 11:21:11 CST 2021
     */
    int updateByPrimaryKey(HotelOrdersDetail record);
}